name: Build

#on:
#push:
#branches: [master]
#pull_request:
#branches: [master]

jobs:
  client:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install
        run: npx pnpm i
      - name: Build
        run: |
          npm run build
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: led
          path: ./**/client/build/*
